[tool.poetry]
name = "site-community"
version = "0.1.0"
description = "Read the Docs website"
authors = ["Read the Docs, Inc"]

[tool.poetry.dependencies]
python = "^3.8"
Jinja2 = "~=3.0.3"
pelican = "4.5.0"
Markdown = "3.1.1"
pelican-related-posts = "1.0.0"
pre-commit = "2.16.0"
pelican-jinja2content = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
