version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0
  node: circleci/node@5.0.2

commands:
  run-lint:
    description: "Run basic checks"
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  run-build:
    description: "Ensure compiled assets are up to date and HTML is valid"
    steps:
      - checkout
      - node/install:
          node-version: '14.18'
      - run: npm ci
      - run: npm run build-assets
      - run:
          name: Ensure built assets are up to date
          command: |
            if [[ `git status readthedocs_theme/ --porcelain` ]]
            then
              echo "ERROR: assets are out of date. Make sure to run 'npm run build' on your branch."
              git status readthedocs_theme/ --porcelain
              exit 1
            fi
      - run: pip install poetry==1.3.2
      - run: poetry -vvv install
      - run: poetry run pelican content -s publishconf.py
      - run: npx html-validate --formatter codeframe output/
  run-publish:
    description: "Publish site on main merge"
    parameters:
      bucket:
        type: string
    steps:
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=3600"
          from: output
          to: <<parameters.bucket>>

jobs:
  lint:
    docker:
      - image: "cimg/node:14.18"
    steps:
      - run-lint: {}
  build:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - attach_workspace:
          at: ~/
      - run-build: {}
      - persist_to_workspace:
          root: ~/
          paths: project
  publish:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - attach_workspace:
          at: ~/
      - run-publish:
          bucket: "s3://readthedocs-static-dev/sites/community"

workflows:
  version: 2
  build:
    jobs:
      - lint
      - build
      - publish:
          requires:
            - lint
            - build
          filters:
            branches:
              only: main
